### ISSUE TITLE
Preference request - Icon size [now too large]

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [wagnerand/SlimAddonsManager#1]
Image says it all: https://www.dropbox.com/sh/yuga3qize00nol3/AAAlgGGryT87Rq3v54aU7AbQa?dl=0&preview=Slim+Add-ons+Manager.png

Top is 10.1, bottom is since the new default icon size was upped to 32. I use a stylish script to reduce everything - I really value real estate on my desktop. Would it be possible to build an option into the add-on for icon size to use - i.e 32 (default) or 16 (optional)? Thanks :)

**Comment by wagnerand** [comment]
As you are using a stylish script, you can use your own rules to make the icon smaller again. Using a standard, non-themed page the row height is now only 2px more than before, which I think is more than reasonable for switching from 16px to 32px icons and does not justify the extra effort of implementing a switch to 16px that only very few people would use because 16px is really small.

**Comment by Thorin-II** [comment]
"As you are using a stylish script, you can use your own rules to make the icon smaller again". I should have looked harder. It's all sorted now: I already had
        max-height: 20px !important;
        max-width: 20px !important;
Just needed to add
        width: 20px !important;
        height: 20px !important;
Thanks.

PS: Totally agree on 32px default and row height only being 2px more as more than reasonable. Didn't mean to imply that it wasn't :)
